"""
Django settings for mysite project.
Generated by 'django-admin startproject' using Django 3.0.2.
For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os, django_heroku
#import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')syu&bleyp%a^0r--do2vveyb@a5j#@vlyygf_$c51gyv02o^y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'QuickTutor.apps.QuicktutorConfig',
    # 'QuickTutor',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #required apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    #includes google provider as a login
    'allauth.socialaccount.providers.google',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"QuickTutor/templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'quicktutordb',
        'USER': 'qtie5',
        'PASSWORD': 'password',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'EST' #Eastern Time Zone

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')
STATICFILES_DIRS = (os.path.join('QuickTutor/static'),)

AUTHENTICATION_BACKENDS = (
    #'allauth' specific authentication methods
    'allauth.account.auth_backends.AuthenticationBackend',

    #Need to login by username in Django admin, regardless of "allauth"
    'django.contrib.auth.backends.ModelBackend',

)

#added in so we don't need to update the admin all the time
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '411759356558-cnc4hoo41ki6f2mcipfh5mpqtn4vogki.apps.googleusercontent.com',
            'secret': '6rnME2c9sAzRcHhN7qzKGL3V',
            'key': ''
        }
    }
}

SITE_ID = 1

ACCOUNT_EMAIL_REQUIRED = True #requires email to be turned over by Google Authentication
ACCOUNT_UNIQUE_EMAIL = True

AUTH_USER_MODEL = "QuickTutor.QTUser"
LOGIN_REDIRECT_URL = "/profile"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST_USER = 'officialquicktutor@gmail.com'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_PASSWORD = "Tutorme11"

TWILIO_ACCT_SID = 'AC751c817bb4d2ee75281aaefeb8020c8e'
TWILIO_CHAT_SID = 'IS8724fa3abd594fcbb9359045de2984d4'
TWILIO_SYNC_SID = 'ISa8ddec424dc603f97d481e1cee0f29ac'
TWILIO_API_SID = 'SKaedc808a7170d0063f7cfecfc3e61c8c'
TWILIO_API_SECRET = 'v7LPQ5XKPwONiF84u0dOShuj6Q8bN7z3'
#heroku settings
django_heroku.settings(locals())
