# Generated by Django 3.0.2 on 2020-02-25 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='name',
            new_name='class_name',
        ),
    ]
