# Generated by Django 3.0.2 on 2020-03-19 20:16

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='date_and_time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='duration_of_session',
        ),
        migrations.AddField(
            model_name='session',
            name='end_date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 21, 16, 19, 248105, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='session',
            name='start_date_and_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
