# Generated by Django 3.0.2 on 2020-03-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qtuser',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
