# Generated by Django 3.0.2 on 2020-03-25 06:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0003_auto_20200325_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 7, 11, 31, 264690, tzinfo=utc)),
        ),
    ]
