# Generated by Django 3.0.2 on 2020-04-11 23:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0003_auto_20200411_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 0, 51, 6, 147588, tzinfo=utc)),
        ),
    ]
