# Generated by Django 3.0.2 on 2020-04-03 15:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0003_auto_20200329_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='course_topic',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 16, 0, 33, 273681, tzinfo=utc)),
        ),
    ]
