# Generated by Django 3.0.2 on 2020-04-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0003_auto_20200411_2322'),
        ('QuickTutor', '0003_auto_20200411_2016'),
    ]

    operations = [
    ]
