# Generated by Django 3.0.2 on 2020-02-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AlterField(
            model_name='qtuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
