# Generated by Django 3.0.2 on 2020-02-25 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0004_auto_20200223_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='qtuser',
            name='first_name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='qtuser',
            name='last_name',
            field=models.TextField(max_length=30),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('classID', models.CharField(default='XX0000', max_length=6, primary_key=True, serialize=False)),
                ('tutorable', models.BooleanField()),
                ('TA_experience', models.BooleanField()),
                ('QTUsers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
