# Generated by Django 3.0.2 on 2020-02-25 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0005_auto_20200225_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='QTUsers',
            new_name='QTUser',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_in_regards_to', models.CharField(max_length=30)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Please rate your experience.')),
                ('description', models.TextField(help_text='Please enter some additional information regarding your experience')),
                ('Author', models.ManyToManyField(related_name='Author', to=settings.AUTH_USER_MODEL)),
                ('Recipient', models.ManyToManyField(related_name='Recipient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
