# Generated by Django 3.0.2 on 2020-04-23 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0006_auto_20200412_1010'),
        ('QuickTutor', '0004_merge_20200412_1111'),
    ]

    operations = [
    ]
