# Generated by Django 3.0.2 on 2020-04-06 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0006_auto_20200403_2225'),
        ('QuickTutor', '0004_auto_20200325_0211'),
    ]

    operations = [
    ]
