# Generated by Django 3.0.2 on 2020-04-11 14:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0007_merge_20200406_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 15, 5, 35, 515170, tzinfo=utc)),
        ),
    ]
