# Generated by Django 3.0.2 on 2020-04-09 03:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0007_merge_20200406_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='price_of_tutor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='student_proposal',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='session',
            name='tutor_proposal',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 4, 53, 28, 256537, tzinfo=utc)),
        ),
    ]
