# Generated by Django 3.0.2 on 2020-04-11 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0008_auto_20200411_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='full_id',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 20, 40, 19, 351236, tzinfo=utc)),
        ),
    ]
