# Generated by Django 3.0.2 on 2020-04-11 19:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0009_auto_20200411_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 20, 42, 17, 367002, tzinfo=utc)),
        ),
    ]
