# Generated by Django 3.0.2 on 2020-04-11 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0009_auto_20200409_0005'),
        ('QuickTutor', '0008_auto_20200411_0905'),
    ]

    operations = [
    ]
