# Generated by Django 3.0.2 on 2020-04-11 21:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0010_merge_20200411_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 22, 12, 6, 694845, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='student_proposal',
            field=models.CharField(choices=[('0', 'pending'), ('1', 'rejected'), ('2', 'accepted')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='session',
            name='tutor_proposal',
            field=models.CharField(choices=[('0', 'pending'), ('1', 'rejected'), ('2', 'accepted')], default='0', max_length=1),
        ),
    ]
