# Generated by Django 3.0.2 on 2020-04-11 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0010_auto_20200411_1442'),
        ('QuickTutor', '0010_merge_20200411_1416'),
    ]

    operations = [
    ]
