# Generated by Django 3.0.2 on 2020-04-11 20:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0011_merge_20200411_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorableclass',
            old_name='Former TA',
            new_name='Former_TA',
        ),
        migrations.AlterField(
            model_name='session',
            name='end_date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 21, 34, 34, 940731, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='student_proposal',
            field=models.CharField(choices=[('0', 'pending'), ('1', 'rejected'), ('2', 'accepted')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='session',
            name='tutor_proposal',
            field=models.CharField(choices=[('0', 'pending'), ('1', 'rejected'), ('2', 'accepted')], default='0', max_length=1),
        ),
    ]
