# Generated by Django 3.0.2 on 2020-04-11 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickTutor', '0012_auto_20200411_1616'),
        ('QuickTutor', '0012_auto_20200411_1534'),
    ]

    operations = [
    ]
